name: Practice Final Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Pytest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-spec pytest-describe pytest-mock

      - name: Run Pytest
        run: pytest --spec test_battery.py

  behave-tests:
    name: Run Behave Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave behave-webdriver selenium
      
      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libnspr4

      - name: Install Chrome
        run: |
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '131.0.6778.109'

      - name: Run Behave Tests
        run: behave features/
