name: Practice Final Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Pytest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-spec pytest-describe

      - name: Run Pytest
        run: pytest --spec test_battery.py

  behave-tests:
    name: Run Behave Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave behave-webdriver
          
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Run Behave Tests
        run: behave features/
